<script setup lang="ts">
import { FileEdit, Plus } from '@lucide/vue'
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'

import BaseButton from '@/components/common/BaseButton.vue'
import ErrorState from '@/components/common/ErrorState.vue'
import SmartTable from '@/components/common/SmartTable.vue'
import StatusBadge from '@/components/common/StatusBadge.vue'
import FillGovernmentFormDialog from '@/components/government/FillGovernmentFormDialog.vue'
import NewSubmissionDialog from '@/components/government/NewSubmissionDialog.vue'
import { ROUTE_NAMES } from '@/constants/routeNames'
import type { SubmissionCreateInput } from '@/services/governmentSubmissionService'
import { useDocumentStore } from '@/stores/documentStore'
import { useGovernmentSubmissionStore } from '@/stores/governmentSubmissionStore'
import { useResultDialogStore } from '@/stores/resultDialogStore'
import type { SmartTableColumn } from '@/types/Table'
import type { SubmissionStatus } from '@/types/Submission'
import { formatDate } from '@/utils/dateFormatter'
import { getDocumentStatusVariant } from '@/utils/documentHelpers'
import { getSubmissionStatusVariant } from '@/utils/submissionHelpers'

const props = defineProps<{
  projectId: string
}>()

const router = useRouter()
const governmentSubmissionStore = useGovernmentSubmissionStore()
const documentStore = useDocumentStore()
const resultDialogStore = useResultDialogStore()

const isCreateDialogOpen = ref(false)
const isCreating = ref(false)
const isFillDialogOpen = ref(false)

const projectSubmissions = computed(() =>
  governmentSubmissionStore.submissionsByProject(props.projectId),
)

// Forms an admin has made fillable (Template Content set, see
// GovernmentFormFormDialog.vue) and still Active -- offered in the Fill
// Form dialog below.
const fillableForms = computed(() =>
  governmentSubmissionStore.forms.filter((form) => form.status === 'Active' && Boolean(form.template)),
)

// PDFs generated by filling in one of those templates for this project
// (see FillGovernmentFormDialog.vue / government_service.fill_form) --
// a Project Document, distinct from the authority-submission workflow
// tracked in the table below.
const agreementDocuments = computed(() =>
  documentStore.documentsByProject(props.projectId).filter((document) => document.type === 'Government Agreement'),
)

function openDocument(documentId: string): void {
  router.push({ name: ROUTE_NAMES.DOCUMENT_VIEWER, params: { documentId } })
}

// Without this, opening this tab directly (rather than via the global
// Government Submissions Workspace page first) leaves the store's
// projects/authorities/forms empty -- New Submission's Authority and
// Form dropdowns would have nothing to select, silently blocking every
// submission from being created.
onMounted(() => {
  if (governmentSubmissionStore.submissions.length === 0) governmentSubmissionStore.loadSubmissions()
  if (documentStore.documents.length === 0) documentStore.loadDocuments()
})

interface SubmissionTableRow {
  [key: string]: unknown
  id: string
  submissionNo: string
  formTitle: string
  authorityName: string
  status: SubmissionStatus
  submittedDate: string
  expectedDecisionDate: string
  decisionDate: string
}

const TABLE_COLUMNS: SmartTableColumn<SubmissionTableRow>[] = [
  { key: 'submissionNo', label: 'Submission No.', sortable: true, width: '140px' },
  { key: 'formTitle', label: 'Form', sortable: true },
  { key: 'authorityName', label: 'Authority', sortable: true },
  { key: 'submittedDate', label: 'Submitted', sortable: true },
  { key: 'expectedDecisionDate', label: 'Estimated Response' },
  { key: 'decisionDate', label: 'Actual Response' },
  { key: 'status', label: 'Status', sortable: true },
]

const tableRows = computed<SubmissionTableRow[]>(() =>
  projectSubmissions.value.map((submission) => ({
    id: submission.id,
    submissionNo: submission.submissionNo,
    formTitle: governmentSubmissionStore.getFormById(submission.formId)?.title ?? 'Unknown Form',
    authorityName: governmentSubmissionStore.getAuthorityById(submission.authorityId)?.name ?? 'Unknown Authority',
    status: submission.status,
    submittedDate: submission.submittedDate ?? '',
    expectedDecisionDate: submission.expectedDecisionDate ?? '',
    decisionDate: submission.decisionDate ?? '',
  })),
)

function openSubmission(row: SubmissionTableRow): void {
  router.push({
    name: ROUTE_NAMES.SUBMISSION_WORKSPACE,
    params: { submissionNo: row.submissionNo },
    query: { projectId: props.projectId },
  })
}

async function handleCreateSubmission(payload: SubmissionCreateInput): Promise<void> {
  isCreating.value = true
  try {
    const submission = await governmentSubmissionStore.createSubmission(payload)
    resultDialogStore.showSuccess('Submission created', `${submission.submissionNo} was created successfully.`)
    isCreateDialogOpen.value = false
  } catch (error) {
    const detail = error instanceof Error && error.message ? error.message : 'Please try again.'
    resultDialogStore.showError('Failed to create submission', detail)
  } finally {
    isCreating.value = false
  }
}
</script>

<template>
  <div class="flex items-center justify-end gap-2 no-print">
    <BaseButton variant="secondary" size="sm" :icon="FileEdit" @click="isFillDialogOpen = true">Fill Form</BaseButton>
    <BaseButton size="sm" :icon="Plus" @click="isCreateDialogOpen = true">New Submission</BaseButton>
  </div>

  <div v-if="agreementDocuments.length > 0" class="flex flex-col gap-2">
    <h3 class="text-sm font-semibold text-text-primary">Filled Agreements &amp; Undertakings</h3>
    <div class="flex flex-col gap-2">
      <button
        v-for="document in agreementDocuments"
        :key="document.id"
        type="button"
        class="flex items-center justify-between gap-3 rounded-lg border border-border-light p-3 text-left transition-colors hover:border-accent-300 hover:bg-accent-50"
        @click="openDocument(document.id)"
      >
        <div class="flex flex-col gap-0.5 truncate">
          <span class="truncate text-sm font-medium text-text-primary">{{ document.title }}</span>
          <span class="text-xs text-text-muted">{{ formatDate(document.uploadDate) }}</span>
        </div>
        <StatusBadge :label="document.status" :variant="getDocumentStatusVariant(document.status)" />
      </button>
    </div>
  </div>

  <ErrorState
    v-if="governmentSubmissionStore.error"
    :description="governmentSubmissionStore.error"
    @retry="governmentSubmissionStore.loadSubmissions"
  />

  <SmartTable
    v-else
    :columns="TABLE_COLUMNS"
    :rows="tableRows"
    row-key="id"
    :loading="governmentSubmissionStore.isLoading"
    :searchable="false"
    empty-title="No submissions yet"
    empty-description="Government submissions filed for this project will appear here."
    @row-click="openSubmission"
  >
    <template #cell-status="{ value }">
      <StatusBadge :label="value as string" :variant="getSubmissionStatusVariant(value as SubmissionStatus)" />
    </template>
    <template #cell-submittedDate="{ value }">
      {{ value ? formatDate(value as string) : 'Not submitted' }}
    </template>
    <template #cell-expectedDecisionDate="{ value }">
      {{ value ? formatDate(value as string) : 'Not set' }}
    </template>
    <template #cell-decisionDate="{ value }">
      {{ value ? formatDate(value as string) : 'Not yet received' }}
    </template>
  </SmartTable>

  <NewSubmissionDialog
    v-model="isCreateDialogOpen"
    :projects="governmentSubmissionStore.projects"
    :authorities="governmentSubmissionStore.authorities"
    :forms="governmentSubmissionStore.forms"
    :default-project-id="projectId"
    :loading="isCreating"
    @confirm="handleCreateSubmission"
  />

  <FillGovernmentFormDialog v-model="isFillDialogOpen" :project-id="projectId" :forms="fillableForms" />
</template>
