import type { AIConfidence } from '@/types/AiReview'

export interface AssistantResponseTemplate {
  details: string
  confidence: AIConfidence
  suggestedActions: string[]
}

export const ASSISTANT_RESPONSE_POOL: AssistantResponseTemplate[] = [
  {
    details:
      'Based on the available project and document context, here is a structured response. This is a mock reply generated by the prototype AI service — connecting a live provider in production only requires a backend change, not a frontend one.',
    confidence: 'high',
    suggestedActions: ['Review manually', 'Share with the project team', 'Attach to project notes'],
  },
  {
    details:
      'The request has been processed against the information currently loaded in this workspace. Some details may be incomplete since this is a simulated response rather than a live model call.',
    confidence: 'medium',
    suggestedActions: ['Review manually', 'Upload a supporting document', 'Ask a follow-up question'],
  },
  {
    details:
      'A draft response has been generated. Treat this as a starting point rather than a final answer — engineering judgement and manual review are still required before acting on it.',
    confidence: 'medium',
    suggestedActions: ['Review manually', 'Edit before using', 'Contact the customer'],
  },
]
