-- Migration 0045: Fillable government form templates + generated
-- agreement documents
--
-- Three parts:
--
-- 1. government_forms gets a `template` TEXT column (the {{token}}
--    merge-field body, written by an admin in Government Forms >
--    Template Content -- see GovernmentFormFormDialog.vue) and a
--    `service_tags` JSON column (the Tagged Services checkbox grid on
--    the same dialog). Both fields already exist on the frontend
--    GovernmentForm type and are already sent by the admin form, but
--    the backend previously had no matching columns, so pydantic's
--    default "ignore extra fields" behavior silently dropped them --
--    nothing was ever actually saved.
--
-- 2. government_forms.category widens to include 'Agreement' and
--    'Legal Undertaking' -- again already valid on the frontend
--    (FORM_CATEGORY_OPTIONS, standardGovernmentForms.ts's seed data)
--    but rejected by the backend's narrower FORM_CATEGORIES enum until
--    now.
--
-- 3. project_documents.type widens to include 'Government Agreement' --
--    the type used for a PDF generated by filling in a government
--    form's template for a specific project (see
--    government_service.fill_form), distinct from 'Municipality Form'
--    (a manually uploaded scan with no generation involved).
--
-- Idempotent -- guarded by information_schema checks throughout, same
-- convention as every other migration here.
--
-- Run this against your MySQL/MariaDB database, e.g.:
--   mysql -u <user> -p <database> < backend/migrations/0045_government_form_template_agreement_document.sql

-- ---------------------------------------------------------------------------
-- Part 1: government_forms.template / government_forms.service_tags
-- ---------------------------------------------------------------------------

SET @db := DATABASE();

SET @exists := (
    SELECT COUNT(*) FROM information_schema.columns
    WHERE table_schema = @db AND table_name = 'government_forms' AND column_name = 'template'
);
SET @sql := IF(@exists = 0,
    'ALTER TABLE government_forms ADD COLUMN template TEXT NULL AFTER preview_url',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @exists := (
    SELECT COUNT(*) FROM information_schema.columns
    WHERE table_schema = @db AND table_name = 'government_forms' AND column_name = 'service_tags'
);
SET @sql := IF(@exists = 0,
    'ALTER TABLE government_forms ADD COLUMN service_tags JSON NULL AFTER template',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ---------------------------------------------------------------------------
-- Part 2: government_forms.category -> add 'Agreement', 'Legal Undertaking'
-- ---------------------------------------------------------------------------

SET @needs_widening := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'government_forms' AND COLUMN_NAME = 'category'
      AND COLUMN_TYPE NOT LIKE '%''Legal Undertaking''%'
);
SET @sql := IF(@needs_widening > 0,
    'ALTER TABLE government_forms MODIFY COLUMN category ENUM(''Building Permit'',''Occupancy Certificate'',''Fire Safety Approval'',''Utility Connection'',''Environmental Clearance'',''Business License'',''Agreement'',''Legal Undertaking'') NOT NULL',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ---------------------------------------------------------------------------
-- Part 3: project_documents.type -> add 'Government Agreement'
-- ---------------------------------------------------------------------------

SET @needs_widening := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'project_documents' AND COLUMN_NAME = 'type'
      AND COLUMN_TYPE NOT LIKE '%''Government Agreement''%'
);
SET @sql := IF(@needs_widening > 0,
    'ALTER TABLE project_documents MODIFY COLUMN type ENUM(''Drawing'',''Report'',''Contract'',''Quotation'',''Municipality Form'',''Calculation Sheet'',''Government Agreement'') NOT NULL',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SELECT 'Migration 0045 complete.' AS status;
