-- Migration 0047: link a generated document back to its source form
--
-- project_documents had no way to tell "this PDF was generated by
-- filling in GovernmentForm X" from "this is an unrelated upload" other
-- than guessing from the document's title -- fragile, and exactly the
-- kind of duplicated/inferred bookkeeping the project's Required
-- Documents checklist (see ProjectOverviewTab.vue) needs to avoid.
-- source_form_id is set once, at generation time (government_service.
-- fill_form), and NULL for every other document (uploads, contracts,
-- quotations, etc).
--
-- ON DELETE SET NULL rather than RESTRICT: deleting a GovernmentForm
-- template later shouldn't be blocked by, or destroy, documents already
-- generated from it -- the generated PDF is a real, independent
-- project record at that point.
--
-- Idempotent -- guarded by information_schema checks, same convention
-- as every other migration here.
--
-- Run this against your MySQL/MariaDB database, e.g.:
--   mysql -u <user> -p <database> < backend/migrations/0047_document_source_form_link.sql

SET @db := DATABASE();

SET @exists := (
    SELECT COUNT(*) FROM information_schema.columns
    WHERE table_schema = @db AND table_name = 'project_documents' AND column_name = 'source_form_id'
);
SET @sql := IF(@exists = 0,
    'ALTER TABLE project_documents ADD COLUMN source_form_id BIGINT UNSIGNED NULL AFTER stage_key',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @constraint_exists := (
    SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'project_documents'
      AND CONSTRAINT_NAME = 'fk_project_documents_source_form'
);
SET @sql := IF(@constraint_exists = 0,
    'ALTER TABLE project_documents ADD CONSTRAINT fk_project_documents_source_form FOREIGN KEY (source_form_id) REFERENCES government_forms(id) ON DELETE SET NULL',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @index_exists := (
    SELECT COUNT(*) FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'project_documents' AND INDEX_NAME = 'idx_project_documents_source_form'
);
SET @sql := IF(@index_exists = 0,
    'CREATE INDEX idx_project_documents_source_form ON project_documents (source_form_id)',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SELECT 'Migration 0047 complete.' AS status;
