export const ROUTE_NAMES = {
  LOGIN: 'login',
  DASHBOARD: 'dashboard',
  PROJECTS: 'projects',
  PROJECT_NEW: 'project-new',
  PROJECT_WORKSPACE: 'project-workspace',
  PAYMENT_PLAN_FORM: 'payment-plan-form',
  QUOTATION_CREATE: 'quotation-create',
  CONTRACT_CREATE: 'contract-create',
  CLIENTS: 'clients',
  CLIENT_NEW: 'client-new',
  CLIENT_WORKSPACE: 'client-workspace',
  GOVERNMENT_FORMS: 'government-forms',
  GOVERNMENT_FORM_FORM: 'government-form-form',
  GOVERNMENT_AUTHORITIES: 'government-authorities',
  GOVERNMENT_SUBMISSIONS: 'government-submissions',
  SUBMISSION_CREATE: 'submission-create',
  SUBMISSION_WORKSPACE: 'submission-workspace',
  SUBMISSION_EDIT: 'submission-edit',
  PROJECT_SUBMISSION_CREATE: 'project-submission-create',
  PROJECT_SUBMISSION_EDIT: 'project-submission-edit',
  PROJECT_SUBMISSION_WORKSPACE: 'project-submission-workspace',
  DOCUMENTS: 'documents',
  DOCUMENT_VIEWER: 'document-viewer',
  KNOWLEDGE_BASE: 'knowledge-base',
  TASKS: 'tasks',
  MY_TASKS: 'my-tasks',
  TASK_CREATE: 'task-create',
  TASK_WORKSPACE: 'task-workspace',
  REPORTS: 'reports',
  REPORT_EXECUTIVE: 'report-executive',
  REPORT_PROJECT: 'report-project',
  REPORT_WORKLOAD: 'report-workload',
  REPORT_EMPLOYEE_ACTIVITY: 'report-employee-activity',
  REPORT_PROJECT_TREE: 'report-project-tree',
  REPORT_CLIENT_PROJECTS: 'report-client-projects',
  REPORT_PAYMENT_LEDGER: 'report-payment-ledger',
  REPORT_EMPLOYEE_PERFORMANCE: 'report-employee-performance',
  REPORT_MONTHLY_FINANCIALS: 'report-monthly-financials',
  ADMIN: 'admin',
  ADMIN_USERS: 'admin-users',
  ADMIN_USER_FORM: 'admin-user-form',
  ADMIN_CATALOGS: 'admin-catalogs',
  ADMIN_DOCUMENTS: 'admin-documents',
  ADMIN_TEMPLATE_FIELD_MAPPER: 'admin-template-field-mapper',
  ADMIN_AI: 'admin-ai',
  ADMIN_COMPANY: 'admin-company',
  ADMIN_EMAIL: 'admin-email',
  ADMIN_SCHEDULED_REPORTS: 'admin-scheduled-reports',
  ADMIN_SCHEDULED_REPORT_FORM: 'admin-scheduled-report-form',
  ADMIN_AUDIT_LOG: 'admin-audit-log',
  // Shared with every authenticated user, not just admins -- see
  // ActivityCalendarPage.vue. Kept the ADMIN_ACTIVITY_CALENDAR name so the
  // Administration module tile (administrationModules.ts) doesn't need a
  // second route pointing at the same page.
  ADMIN_ACTIVITY_CALENDAR: 'activity-calendar',
  MY_PROFILE: 'my-profile',
  SITE_PORTAL_LOGIN: 'site-portal-login',
  SITE_PORTAL_CALENDAR: 'site-portal-calendar',
  SITE_PORTAL_REPORT: 'site-portal-report',
  STATUS_REPORTS_INBOX: 'status-reports-inbox',
  MESSAGE_CENTRE: 'message-centre',
  PAYMENTS: 'payments',
  NOT_FOUND: 'not-found',
} as const
