export const ROUTE_NAMES = {
  LOGIN: 'login',
  DASHBOARD: 'dashboard',
  PROJECTS: 'projects',
  PROJECT_NEW: 'project-new',
  PROJECT_WORKSPACE: 'project-workspace',
  PROJECT_SUMMARY_REPORT: 'project-summary-report',
  CLIENTS: 'clients',
  CLIENT_NEW: 'client-new',
  CLIENT_WORKSPACE: 'client-workspace',
  GOVERNMENT_FORMS: 'government-forms',
  GOVERNMENT_AUTHORITIES: 'government-authorities',
  GOVERNMENT_SUBMISSIONS: 'government-submissions',
  SUBMISSION_WORKSPACE: 'submission-workspace',
  DOCUMENTS: 'documents',
  DOCUMENT_VIEWER: 'document-viewer',
  DOCUMENT_REVIEW: 'document-review',
  TASKS: 'tasks',
  MY_TASKS: 'my-tasks',
  REPORTS: 'reports',
  REPORT_EXECUTIVE: 'report-executive',
  REPORT_PROJECT: 'report-project',
  REPORT_WORKLOAD: 'report-workload',
  ADMIN: 'admin',
  ADMIN_USERS: 'admin-users',
  ADMIN_SERVICE_CATALOG: 'admin-service-catalog',
  ADMIN_TYPE_ACTIVITY_CATALOG: 'admin-type-activity-catalog',
  ADMIN_PERMIT_CATALOG: 'admin-permit-catalog',
  ADMIN_EXECUTION_STEPS: 'admin-execution-steps',
  ADMIN_FORMS: 'admin-forms',
  ADMIN_AI: 'admin-ai',
  ADMIN_COMPANY: 'admin-company',
  ADMIN_AUDIT_LOG: 'admin-audit-log',
  // Shared with every authenticated user, not just admins -- see
  // ActivityCalendarPage.vue. Kept the ADMIN_ACTIVITY_CALENDAR name so the
  // Administration module tile (administrationModules.ts) doesn't need a
  // second route pointing at the same page.
  ADMIN_ACTIVITY_CALENDAR: 'activity-calendar',
  CUSTOMER_PORTAL_LOGIN: 'customer-portal',
  CUSTOMER_PORTAL_PROJECTS: 'customer-portal-projects',
  CUSTOMER_PORTAL_PROJECT: 'customer-project',
  SITE_PORTAL_LOGIN: 'site-portal-login',
  SITE_PORTAL_CALENDAR: 'site-portal-calendar',
  SITE_PORTAL_REPORT: 'site-portal-report',
  STATUS_REPORTS_INBOX: 'status-reports-inbox',
  MESSAGE_CENTRE: 'message-centre',
  PAYMENTS: 'payments',
  NOT_FOUND: 'not-found',
} as const
