export const ROUTE_NAMES = {
  LOGIN: 'login',
  DASHBOARD: 'dashboard',
  PROJECTS: 'projects',
  PROJECT_NEW: 'project-new',
  PROJECT_WORKSPACE: 'project-workspace',
  CLIENTS: 'clients',
  CLIENT_NEW: 'client-new',
  CLIENT_WORKSPACE: 'client-workspace',
  GOVERNMENT_FORMS: 'government-forms',
  GOVERNMENT_AUTHORITIES: 'government-authorities',
  GOVERNMENT_SUBMISSIONS: 'government-submissions',
  DOCUMENTS: 'documents',
  DOCUMENT_VIEWER: 'document-viewer',
  DOCUMENT_REVIEW: 'document-review',
  TASKS: 'tasks',
  MY_TASKS: 'my-tasks',
  REPORTS: 'reports',
  REPORT_EXECUTIVE: 'report-executive',
  REPORT_PROJECT: 'report-project',
  REPORT_WORKLOAD: 'report-workload',
  ADMIN: 'admin',
  ADMIN_USERS: 'admin-users',
  ADMIN_WORKFLOWS: 'admin-workflows',
  ADMIN_FORMS: 'admin-forms',
  ADMIN_AI: 'admin-ai',
  ADMIN_COMPANY: 'admin-company',
  ADMIN_AUDIT_LOG: 'admin-audit-log',
  // Shared with every authenticated user, not just admins -- see
  // ActivityCalendarPage.vue. Kept the ADMIN_ACTIVITY_CALENDAR name so the
  // Administration module tile (administrationModules.ts) doesn't need a
  // second route pointing at the same page.
  ADMIN_ACTIVITY_CALENDAR: 'activity-calendar',
  CUSTOMER_PORTAL_LOGIN: 'customer-portal',
  CUSTOMER_PORTAL_PROJECT: 'customer-project',
  MESSAGE_CENTRE: 'message-centre',
  PAYMENTS: 'payments',
  NOT_FOUND: 'not-found',
} as const
