import { createRouter, createWebHistory } from 'vue-router'

import { ROUTE_NAMES } from '@/constants/routeNames'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      redirect: '/login',
    },
    {
      path: '/login',
      name: ROUTE_NAMES.LOGIN,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Login' },
      meta: { layout: 'auth' },
    },
    {
      path: '/status',
      name: ROUTE_NAMES.CUSTOMER_STATUS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Project Status Tracker' },
      meta: { layout: 'auth' },
    },
    {
      path: '/dashboard',
      name: ROUTE_NAMES.DASHBOARD,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Executive Dashboard' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/projects',
      name: ROUTE_NAMES.PROJECTS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Project Explorer' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/projects/new',
      name: ROUTE_NAMES.PROJECT_NEW,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'New Project Wizard' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/projects/:projectId',
      name: ROUTE_NAMES.PROJECT_WORKSPACE,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Project Workspace' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/government/forms',
      name: ROUTE_NAMES.GOVERNMENT_FORMS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Government Forms Library' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/government/authorities',
      name: ROUTE_NAMES.GOVERNMENT_AUTHORITIES,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Authority Directory' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/government/submissions',
      name: ROUTE_NAMES.GOVERNMENT_SUBMISSIONS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Government Submission Workspace' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/documents',
      name: ROUTE_NAMES.DOCUMENTS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Document Repository' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/documents/:documentId',
      name: ROUTE_NAMES.DOCUMENT_VIEWER,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Document Viewer' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/documents/:documentId/review',
      name: ROUTE_NAMES.DOCUMENT_REVIEW,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'AI Document Review' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/tasks',
      name: ROUTE_NAMES.TASKS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Task Board' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/tasks/my',
      name: ROUTE_NAMES.MY_TASKS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'My Tasks' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/reports',
      name: ROUTE_NAMES.REPORTS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Dashboard Reports' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/admin/users',
      name: ROUTE_NAMES.ADMIN_USERS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'User Management' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/admin/workflows',
      name: ROUTE_NAMES.ADMIN_WORKFLOWS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Workflow Configuration' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/admin/forms',
      name: ROUTE_NAMES.ADMIN_FORMS,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Government Forms Management' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/admin/ai',
      name: ROUTE_NAMES.ADMIN_AI,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'AI Configuration' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/admin/company',
      name: ROUTE_NAMES.ADMIN_COMPANY,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Company Settings' },
      meta: { layout: 'dashboard' },
    },
    {
      path: '/:pathMatch(.*)*',
      name: ROUTE_NAMES.NOT_FOUND,
      component: () => import('@/pages/PlaceholderPage.vue'),
      props: { title: 'Page Not Found' },
      meta: { layout: 'auth' },
    },
  ],
})

export default router
