// 'Government Agreement' is a PDF generated by filling in a government
// form's template for this project (see governmentFormService.fillForm)
// -- distinct from 'Municipality Form', a manually uploaded scan with no
// generation involved.
export type DocumentType =
  | 'Drawing'
  | 'Report'
  | 'Contract'
  | 'Quotation'
  | 'Municipality Form'
  | 'Calculation Sheet'
  | 'Government Agreement'

export type DocumentStatus = 'Draft' | 'Under Review' | 'Approved' | 'Rejected'

export interface ProjectDocument {
  id: string
  projectId: string
  title: string
  type: DocumentType
  revision: string
  uploadedBy: string
  uploadDate: string
  status: DocumentStatus
  // Both null for a link-only document (no uploaded file) -- see
  // externalLink below.
  fileSize: string | null
  originalFilename: string | null
  // A link to a document that lives outside the app -- optional,
  // independent of whether a file was also uploaded.
  externalLink: string | null
  // Which GovernmentForm this was generated from (see
  // governmentFormService.fillForm) -- null for anything not generated
  // that way (uploads, contracts, quotations, etc). Lets the Required
  // Documents checklist check "has this form been filled for this
  // project" via a real link instead of guessing from the title.
  sourceFormId: string | null
}

export type DocumentViewMode = 'grid' | 'table'

// The three project-level categories a document can be added under with
// just a name and a path/link -- the file itself is stored outside the
// app (a shared drive, a government portal, a scan on the office server).
// "Customer ID" is shown alongside these in the Documents tab but is a
// fourth, read-only category sourced from the client's own onboarding
// documents (ClientDocument), not this type.
export type ProjectLinkDocumentCategory = 'Property' | 'Government' | 'Others' | 'Project Closure'

export interface ProjectLinkDocument {
  id: string
  projectId: string
  category: ProjectLinkDocumentCategory
  name: string
  path: string
  addedBy: string
  addedDate: string
}

export interface DocumentVersion {
  id: string
  documentId: string
  revision: string
  uploadedBy: string
  uploadDate: string
  notes: string
  originalFilename: string
}
